name: test
version: 1.0.0
main: me.tech.App
description: A test plugin
author: toki32
website: https://xserver.com
api-version: 1.16
commands:
  login:
    description: Log in to play
    usage: /login your_password
  register:
    description: Register to play
    usage: /register your_password
  change_password:
    description: Change you password
    usage: /change_password old_password new_password
  delete:
    description: Delete your account
    usage: /delete your_password
  god:
    description: asd
    usage: asdasd
  opbow:
    description: asd
    usage: asdasd
  vanish:
    description: asd
    usage: asdasd
  pls:
    description: asd
    usage: asdasd
  home:
    description: Teleports you to your bed
    usage: /home